/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoWeWorkWithRouteImport } from './routes/who-we-work-with'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesInteriorRenovationsRouteImport } from './routes/services.interior-renovations'
import { Route as ServicesCustomMillworkRouteImport } from './routes/services.custom-millwork'
import { Route as ServicesCommercialRouteImport } from './routes/services.commercial'
import { Route as PortfolioBeforeAfterRouteImport } from './routes/portfolio.before-after'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const WhoWeWorkWithRoute = WhoWeWorkWithRouteImport.update({
  id: '/who-we-work-with',
  path: '/who-we-work-with',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInteriorRenovationsRoute =
  ServicesInteriorRenovationsRouteImport.update({
    id: '/services/interior-renovations',
    path: '/services/interior-renovations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomMillworkRoute = ServicesCustomMillworkRouteImport.update({
  id: '/services/custom-millwork',
  path: '/services/custom-millwork',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCommercialRoute = ServicesCommercialRouteImport.update({
  id: '/services/commercial',
  path: '/services/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioBeforeAfterRoute = PortfolioBeforeAfterRouteImport.update({
  id: '/before-after',
  path: '/before-after',
  getParentRoute: () => PortfolioRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/who-we-work-with': typeof WhoWeWorkWithRoute
  '/portfolio/before-after': typeof PortfolioBeforeAfterRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/custom-millwork': typeof ServicesCustomMillworkRoute
  '/services/interior-renovations': typeof ServicesInteriorRenovationsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/who-we-work-with': typeof WhoWeWorkWithRoute
  '/portfolio/before-after': typeof PortfolioBeforeAfterRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/custom-millwork': typeof ServicesCustomMillworkRoute
  '/services/interior-renovations': typeof ServicesInteriorRenovationsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/who-we-work-with': typeof WhoWeWorkWithRoute
  '/portfolio/before-after': typeof PortfolioBeforeAfterRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/custom-millwork': typeof ServicesCustomMillworkRoute
  '/services/interior-renovations': typeof ServicesInteriorRenovationsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/who-we-work-with'
    | '/portfolio/before-after'
    | '/services/commercial'
    | '/services/custom-millwork'
    | '/services/interior-renovations'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/who-we-work-with'
    | '/portfolio/before-after'
    | '/services/commercial'
    | '/services/custom-millwork'
    | '/services/interior-renovations'
    | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/who-we-work-with'
    | '/portfolio/before-after'
    | '/services/commercial'
    | '/services/custom-millwork'
    | '/services/interior-renovations'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  WhoWeWorkWithRoute: typeof WhoWeWorkWithRoute
  ServicesCommercialRoute: typeof ServicesCommercialRoute
  ServicesCustomMillworkRoute: typeof ServicesCustomMillworkRoute
  ServicesInteriorRenovationsRoute: typeof ServicesInteriorRenovationsRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who-we-work-with': {
      id: '/who-we-work-with'
      path: '/who-we-work-with'
      fullPath: '/who-we-work-with'
      preLoaderRoute: typeof WhoWeWorkWithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/interior-renovations': {
      id: '/services/interior-renovations'
      path: '/services/interior-renovations'
      fullPath: '/services/interior-renovations'
      preLoaderRoute: typeof ServicesInteriorRenovationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-millwork': {
      id: '/services/custom-millwork'
      path: '/services/custom-millwork'
      fullPath: '/services/custom-millwork'
      preLoaderRoute: typeof ServicesCustomMillworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/commercial': {
      id: '/services/commercial'
      path: '/services/commercial'
      fullPath: '/services/commercial'
      preLoaderRoute: typeof ServicesCommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/before-after': {
      id: '/portfolio/before-after'
      path: '/before-after'
      fullPath: '/portfolio/before-after'
      preLoaderRoute: typeof PortfolioBeforeAfterRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioBeforeAfterRoute: typeof PortfolioBeforeAfterRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioBeforeAfterRoute: PortfolioBeforeAfterRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  WhoWeWorkWithRoute: WhoWeWorkWithRoute,
  ServicesCommercialRoute: ServicesCommercialRoute,
  ServicesCustomMillworkRoute: ServicesCustomMillworkRoute,
  ServicesInteriorRenovationsRoute: ServicesInteriorRenovationsRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
