/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoWeWorkWithRouteImport } from './routes/who-we-work-with'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesInteriorRenovationsRouteImport } from './routes/services.interior-renovations'
import { Route as ServicesCustomMillworkRouteImport } from './routes/services.custom-millwork'
import { Route as ServicesCommercialRouteImport } from './routes/services.commercial'
import { Route as PortfolioBeforeAfterRouteImport } from './routes/portfolio.before-after'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AboutOurProcessRouteImport } from './routes/about.our-process'
import { Route as AboutMillworkShopRouteImport } from './routes/about.millwork-shop'
import { Route as AboutCertificationsAffiliationsRouteImport } from './routes/about.certifications-affiliations'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const WhoWeWorkWithRoute = WhoWeWorkWithRouteImport.update({
  id: '/who-we-work-with',
  path: '/who-we-work-with',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInteriorRenovationsRoute =
  ServicesInteriorRenovationsRouteImport.update({
    id: '/services/interior-renovations',
    path: '/services/interior-renovations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomMillworkRoute = ServicesCustomMillworkRouteImport.update({
  id: '/services/custom-millwork',
  path: '/services/custom-millwork',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCommercialRoute = ServicesCommercialRouteImport.update({
  id: '/services/commercial',
  path: '/services/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioBeforeAfterRoute = PortfolioBeforeAfterRouteImport.update({
  id: '/before-after',
  path: '/before-after',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AboutOurProcessRoute = AboutOurProcessRouteImport.update({
  id: '/our-process',
  path: '/our-process',
  getParentRoute: () => AboutRoute,
} as any)
const AboutMillworkShopRoute = AboutMillworkShopRouteImport.update({
  id: '/millwork-shop',
  path: '/millwork-shop',
  getParentRoute: () => AboutRoute,
} as any)
const AboutCertificationsAffiliationsRoute =
  AboutCertificationsAffiliationsRouteImport.update({
    id: '/certifications-affiliations',
    path: '/certifications-affiliations',
    getParentRoute: () => AboutRoute,
  } as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/who-we-work-with': typeof WhoWeWorkWithRoute
  '/about/certifications-affiliations': typeof AboutCertificationsAffiliationsRoute
  '/about/millwork-shop': typeof AboutMillworkShopRoute
  '/about/our-process': typeof AboutOurProcessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/before-after': typeof PortfolioBeforeAfterRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/custom-millwork': typeof ServicesCustomMillworkRoute
  '/services/interior-renovations': typeof ServicesInteriorRenovationsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/who-we-work-with': typeof WhoWeWorkWithRoute
  '/about/certifications-affiliations': typeof AboutCertificationsAffiliationsRoute
  '/about/millwork-shop': typeof AboutMillworkShopRoute
  '/about/our-process': typeof AboutOurProcessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/before-after': typeof PortfolioBeforeAfterRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/custom-millwork': typeof ServicesCustomMillworkRoute
  '/services/interior-renovations': typeof ServicesInteriorRenovationsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/who-we-work-with': typeof WhoWeWorkWithRoute
  '/about/certifications-affiliations': typeof AboutCertificationsAffiliationsRoute
  '/about/millwork-shop': typeof AboutMillworkShopRoute
  '/about/our-process': typeof AboutOurProcessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/before-after': typeof PortfolioBeforeAfterRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/custom-millwork': typeof ServicesCustomMillworkRoute
  '/services/interior-renovations': typeof ServicesInteriorRenovationsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faqs'
    | '/portfolio'
    | '/testimonials'
    | '/who-we-work-with'
    | '/about/certifications-affiliations'
    | '/about/millwork-shop'
    | '/about/our-process'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/portfolio/before-after'
    | '/services/commercial'
    | '/services/custom-millwork'
    | '/services/interior-renovations'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faqs'
    | '/portfolio'
    | '/testimonials'
    | '/who-we-work-with'
    | '/about/certifications-affiliations'
    | '/about/millwork-shop'
    | '/about/our-process'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/portfolio/before-after'
    | '/services/commercial'
    | '/services/custom-millwork'
    | '/services/interior-renovations'
    | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faqs'
    | '/portfolio'
    | '/testimonials'
    | '/who-we-work-with'
    | '/about/certifications-affiliations'
    | '/about/millwork-shop'
    | '/about/our-process'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/portfolio/before-after'
    | '/services/commercial'
    | '/services/custom-millwork'
    | '/services/interior-renovations'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  TestimonialsRoute: typeof TestimonialsRoute
  WhoWeWorkWithRoute: typeof WhoWeWorkWithRoute
  ServicesCommercialRoute: typeof ServicesCommercialRoute
  ServicesCustomMillworkRoute: typeof ServicesCustomMillworkRoute
  ServicesInteriorRenovationsRoute: typeof ServicesInteriorRenovationsRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who-we-work-with': {
      id: '/who-we-work-with'
      path: '/who-we-work-with'
      fullPath: '/who-we-work-with'
      preLoaderRoute: typeof WhoWeWorkWithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/interior-renovations': {
      id: '/services/interior-renovations'
      path: '/services/interior-renovations'
      fullPath: '/services/interior-renovations'
      preLoaderRoute: typeof ServicesInteriorRenovationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-millwork': {
      id: '/services/custom-millwork'
      path: '/services/custom-millwork'
      fullPath: '/services/custom-millwork'
      preLoaderRoute: typeof ServicesCustomMillworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/commercial': {
      id: '/services/commercial'
      path: '/services/commercial'
      fullPath: '/services/commercial'
      preLoaderRoute: typeof ServicesCommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/before-after': {
      id: '/portfolio/before-after'
      path: '/before-after'
      fullPath: '/portfolio/before-after'
      preLoaderRoute: typeof PortfolioBeforeAfterRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/about/our-process': {
      id: '/about/our-process'
      path: '/our-process'
      fullPath: '/about/our-process'
      preLoaderRoute: typeof AboutOurProcessRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/millwork-shop': {
      id: '/about/millwork-shop'
      path: '/millwork-shop'
      fullPath: '/about/millwork-shop'
      preLoaderRoute: typeof AboutMillworkShopRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/certifications-affiliations': {
      id: '/about/certifications-affiliations'
      path: '/certifications-affiliations'
      fullPath: '/about/certifications-affiliations'
      preLoaderRoute: typeof AboutCertificationsAffiliationsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutCertificationsAffiliationsRoute: typeof AboutCertificationsAffiliationsRoute
  AboutMillworkShopRoute: typeof AboutMillworkShopRoute
  AboutOurProcessRoute: typeof AboutOurProcessRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutCertificationsAffiliationsRoute: AboutCertificationsAffiliationsRoute,
  AboutMillworkShopRoute: AboutMillworkShopRoute,
  AboutOurProcessRoute: AboutOurProcessRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioBeforeAfterRoute: typeof PortfolioBeforeAfterRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioBeforeAfterRoute: PortfolioBeforeAfterRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  TestimonialsRoute: TestimonialsRoute,
  WhoWeWorkWithRoute: WhoWeWorkWithRoute,
  ServicesCommercialRoute: ServicesCommercialRoute,
  ServicesCustomMillworkRoute: ServicesCustomMillworkRoute,
  ServicesInteriorRenovationsRoute: ServicesInteriorRenovationsRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
